backend:
  name: github
  repo: Alvarorfontana/contexto.politico
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "noticias"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
